name: Deploy to Vercel Production

# Trigger deployment when CI Pipeline completes successfully
on:
  workflow_run:
    workflows: ["CI Pipeline"]  # This must match the name of your CI workflow
    types:
      - completed  # Trigger only after CI completion

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (adjust version as per your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or another Node.js version if needed

      # Step 3: Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install -g vercel

     # Step 4: Deploy to Vercel Production
      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

